martinzuern/cards-offending-mankind

root-types.ts

Root types

---

 .github/workflows/backend.yml

(cherry picked from commit 72c77d78f8102b9a773f1c0e5b5d4eaf1d873741)

Added first GitHub action

---

backend/__tests__/game.service.ts
backend/server/services/db.service.ts
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts

Few small bugfixes in the backend

Backend assert messages

---

backend/package.json
backend/yarn.lock

Backend: updated dependencies

---

backend/.eslintrc.js
backend/package.json
backend/server/common/server.ts
backend/server/sockets/controllers/games/controller.ts
backend/yarn.lock

Add helmet, adjust CORS

---

backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
types/Game.ts

Backend timeout features

---

Dockerfile
backend/__tests__/game.service.ts
backend/package.json
backend/root-types.ts
backend/server/api/controllers/games/controller.ts
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
backend/server/sockets/controllers/games/queue.ts
backend/server/sockets/controllers/games/socket.ts
backend/yarn.lock
docker-compose.yml

Refactor timeout

---

backend/package.json
backend/server/common/server.ts
backend/server/services/db.service.ts
backend/server/sockets/controllers/games/queue.ts
backend/server/sockets/middlewares/error.handler.ts
backend/yarn.lock

Added sentry to backend

---

backend/server/common/server.ts

Added code to serve the vue frontend

---

frontend/package.json
frontend/src/components/AccessGame/GameState.vue
frontend/src/components/AccessGame/InGame.vue
frontend/src/components/GameForm/CreateGameForm.vue
frontend/src/components/GameForm/JoinGameForm.vue
frontend/yarn.lock

Added vue multiselect

---

backend/package.json
backend/server/common/server.ts
backend/yarn.lock
frontend/.eslintrc.js
frontend/public/index.html
frontend/src/components/AccessGame/GameState.vue

Improvements

---

frontend/src/components/AccessGame/Countdown.vue
frontend/src/components/AccessGame/Deck.vue
frontend/src/components/AccessGame/GameState.vue

Frontend improvements

---

backend/__tests__/__snapshots__/game.controller.ts.snap
backend/__tests__/__snapshots__/game.service.ts.snap
backend/__tests__/__snapshots__/game.socket.ts.snap
backend/server/common/api.yml
backend/server/common/server.ts
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
frontend/src/components/GameForm/CreateGameForm.vue
frontend/src/components/InGame/GameCreated.vue
frontend/src/components/InGame/GameEnded.vue
frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/helper/Leaderboard.vue
types/Game.ts

Add AI Player

---

frontend/src/App.vue
frontend/src/components/GameForm/CreateGameForm.vue
frontend/src/components/GameForm/GameForm.vue
frontend/src/sass/_variables.sass

Login improvements

---

frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/helper/GamePlaying.vue

Flying in cards

---

backend/__tests__/game.socket.ts
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
backend/server/sockets/controllers/games/socket.ts
backend/tsconfig.json
frontend/package.json
frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/InGame.vue
frontend/src/components/InGame/helper/GameJudging.vue
frontend/src/main.ts
frontend/tsconfig.json
frontend/typings.d.ts
frontend/yarn.lock

Further frontend improvements 

---

Dockerfile
backend/server/common/server.ts
docker-compose.prod.yml
frontend/src/main.ts

56 sentry frontend

---

frontend/package.json
frontend/src/App.vue
frontend/src/components/GameForm/GameForm.vue
frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/InGame.vue
frontend/src/components/InGame/helper/Card.vue
frontend/src/components/InGame/helper/Countdown.vue
frontend/src/components/InGame/helper/GameJudging.vue
frontend/src/components/InGame/helper/GamePlaying.vue
frontend/src/components/InGame/helper/Leaderboard.vue
frontend/src/helpers/FlowType.ts
frontend/src/sass/_variables.sass
frontend/yarn.lock

Improve card selection

---

backend/__tests__/__snapshots__/game.controller.ts.snap
backend/__tests__/__snapshots__/game.service.ts.snap
backend/__tests__/__snapshots__/game.socket.ts.snap
backend/server/common/api.yml
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
backend/server/sockets/controllers/games/socket.ts
frontend/src/App.vue
frontend/src/components/GameForm/CreateGameForm.vue
frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/helper/GameJudging.vue
frontend/src/components/InGame/helper/GamePlaying.vue
frontend/src/sass/_variables.sass
types/Game.ts

Added feature to discard cards

---

backend/__tests__/__snapshots__/game.controller.ts.snap
backend/__tests__/__snapshots__/game.service.ts.snap
backend/__tests__/__snapshots__/game.socket.ts.snap
backend/__tests__/game.service.ts
backend/__tests__/game.socket.ts
backend/server/api/middlewares/error.handler.ts
backend/server/common/api.yml
backend/server/common/openapi.ts
backend/server/services/game.service.ts
backend/server/sockets/controllers/games/controller.ts
backend/server/sockets/controllers/games/queue.ts
backend/server/sockets/controllers/games/socket.ts
docker-compose.yml
frontend/src/App.vue
frontend/src/components/GameForm/CreateGameForm.vue
frontend/src/components/InGame/GameCreated.vue
frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/InGame.vue
frontend/src/components/InGame/helper/GameJudging.vue
frontend/src/components/InGame/helper/GamePlaying.vue
frontend/src/helpers/SocketEmitter.ts
types/Game.ts
types/Messages.ts

Add skipping of prompt card

---

frontend/src/components/InGame/GameRunning.vue
frontend/src/components/InGame/helper/Leaderboard.vue

added leaderboard label when screensize allows for it

---

frontend/src/App.vue
frontend/src/components/GitHubCorners.vue
frontend/src/components/InGame/helper/Card.vue
frontend/src/router/index.ts
frontend/src/views/Legal.vue

Added legal page

---

backend/__tests__/__snapshots__/game.service.ts.snap
backend/__tests__/__snapshots__/game.socket.ts.snap
backend/__tests__/__snapshots__/packs.controller.ts.snap
backend/package.json
backend/server/services/packs.service.ts
backend/yarn.lock
frontend/package.json
frontend/src/components/InGame/helper/Card.vue
frontend/src/main.ts
frontend/yarn.lock
types/Cards.ts

Added card details
